targets:
  $default:
    builders:
      freezed:
        enabled: true
        generate_for:
          - lib/src/**/*.dart
      json_serializable:
        enabled: true
        generate_for:
          - lib/src/**/*.dart
      retrofit_generator:
        enabled: true
        generate_for:
          - lib/src/**/*_datasource.dart
